spring:
  application:
    name: aura-core-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Aura}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
server:
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret-key: ${JWT_SECRET_KEY:change-me-to-a-strong-32-byte-secret-key}
  expire-time: ${JWT_EXPIRE_TIME:86400000}

logging:
  level:
    com.aura.core.mapper: trace
